### ISSUE TITLE
need an option to preserve source file key order

### ISSUE THREAD

**Issue by kghenderson** [hjson/hjson-go#50]
i'm trying to remain compatible with a python implementation of the hjson format, and need the keys to remain in order.

this is preventing me from being able to utilize this tool due to it's key sorting in the output. 

i understand that in go, a map is not guaranteed an order, but the keys could be imported into a list on read and exported back out in the same order that they appear, i.e. to simulate a python 'ordered dictionary.

this doesn't need to be the default behaviour since often the sorting is desired, but as a compatibility option or flag to 'preserve key order' would be ideal.

thank you for considering.

**Comment by trobro** [comment]
Support for ordered maps was implemented two months ago, make sure that you are using release 4.2.0 or newer. Just as you say, you cannot use a variable of type `map` or `interface{}` as destination. Here is an example of an ordered map you can use as destination (because it supports JSON serialization and deserialization):

https://github.com/iancoleman/orderedmap

**Comment by kghenderson** [comment]
this is great news, follow up question though: is this available through the cli? i don't see it in the help options. 
haha, smh, i see that ordered keys is the prime feature of https://github.com/hjson/hjson-go/releases/tag/v4.2.0
but the cli still seems to be sorting.

**Comment by trobro** [comment]
True, `hjson-cli` always sorts the keys. I'll see about making a new release with an optional flag `-preserveKeyOrder` for `hjson-cli`.

**Comment by kghenderson** [comment]
^ thank you so much :-)  if it's not too much trouble, it might be nice to drop the version number into the -h help message.

**Comment by trobro** [comment]
> if it's not too much trouble, it might be nice to drop the version number into the -h help message.

Thanks for the suggestion, but in my experience cli tools on nix-systems do not display the version number in the help message but instead display it if `-v`, `--version` or `version` is given as argument. So I'll keep the current implementation of that (displays version if `-v` is given as argument, was added in release 4.0.0).

**Comment by kghenderson** [comment]
hmm, i'm trying to figure out what's happening but maybe you can help me (sorry, still somewhat new to go)
just unininstalled and reinstalled and got:
```
❯ go install github.com/hjson/hjson-go/hjson-cli@latest
go: downloading github.com/hjson/hjson-go v3.3.0+incompatible
```
which is the wrong version (3.3):

trying to get latest version explicitly:
```
❯ go install github.com/hjson/hjson-go/hjson-cli@v4.2.0
go: github.com/hjson/hjson-go/hjson-cli@v4.2.0: github.com/hjson/hjson-go/hjson-cli@v4.2.0: invalid version: unknown revision hjson-cli/v4.2.0
```
and it seems a main package is needed, because
```
❯ go install github.com/hjson/hjson-go@latest
package github.com/hjson/hjson-go is not a main package
```

so i'm not sure how to fix this with `go install` (go version 1.19.3 darwin/amd64)

**Comment by trobro** [comment]
Thanks for pointing that out, there is an error in the documentation, I'll fix it. This is the correct command:

```
go install github.com/hjson/hjson-go/v4/hjson-cli@latest
```

In Go the different major versions of a package are treated like different packages, that's why I had to add `/v4/` in the path to get version 4.x. But it wasn't always like that in Go, that's why major version 1, 2 and 3 of `hjson-go` are treated as the same package, so you get version 3.x if you don't specify a major version.

One more problem I noticed now is that `hjson-cli -v` won't display the version if `hjson-cli` was installed using the command I mentioned here above. This gets the version from the latest git tag:

```
go install -ldflags "-w -s -X main.Version=`git ls-remote --tags --sort=v:refname https://github.com/hjson/hjson-go | tail -1 | sed "s/.*tags\///"`" github.com/hjson/hjson-go/v4/hjson-cli@latest
```

Getting a bit overly verbose there, so I'll have a look at using `debug.ReadBuildInfo()` in the code instead to get the module version...

**Comment by trobro** [comment]
The tool can also be downloaded pre-built, if Go is not installed on the local computer:

https://hjson.github.io/users-bin.html

**Comment by kghenderson** [comment]
awesome, this was super helpful, thank you, all squared with retrieving 4.2.0 now, thanks!

**Comment by trobro** [comment]
Added *hjson-cli* argument `-preserveKeyOrder` and created release v4.3.0.

**Comment by kghenderson** [comment]
just wanted to say we are now using this and have validated the results.
thanks very much! :-D

**Comment by trobro** [comment]
Great, I'm glad it was useful. :)
