### ISSUE TITLE
Preserve comments on source file

### ISSUE THREAD

**Issue by mohsenari** [hjson/hjson-go#51]
I was wondering if there is a way to Unmarshal `hjson` to a go struct but preserve arbitrary comments on the source json. For example if my hjson looks like this:
```hjson
{
// random comment
  "foo": "bar",
  "foo2": "bar2"
}
```
I want to preserve a comment on a random line in the json, unmarshal the file to a go struct, change `bar` to `bar-modified`.
Then marshal and save to file.

Is it possible to preserve comments when you don't know which line might have a comment on it?

**Comment by trobro** [comment]
I don't know of any solution for structs, because the tags on structs are declared in the struct declaration and cannot be altered after that.

One solution I could do is to create a special `hjson.Value` interface in `hjson-go` similar to the `Value` class in `hjson-cpp`. So that Hjson can be unmarshalled into a tree of `hjson.Value` objects where comments can be read and written on each object.

**Comment by mohsenari** [comment]
Yeah I think that could work. To be clear my goal is not to read & write comments even though it would be a nice feature to have. My goal is to preserve comments, and change the key-value data. Then save my changed data back to json while keeping the comments unchanged.

**Comment by trobro** [comment]
In the new release v4.3.0 you can read-change-write with preserved comments and whitespace for example like this:

```go
var node hjson.Node
if err := hjson.Unmarshal(txt, &node); err != nil {
  panic(err)
}
if _, _, err := node.SetKey("myKey", "myValue"); err != nil {
  panic(err)
}
outBytes, err := hjson.Marshal(node)
if err != nil {
  panic(err)
}
```
